# Machine Learning 1 - Exercise Sheet 1

## Viktor Vironski (4330455), Andy Disser (5984875), Trung (Matrikelnummer)



### Exercise 1. Min-Max normalization

In [128]:
from sklearn import datasets
import numpy as np

# implement Min-Max Normalization Function for range 0 to 1

def min_max_scale( data: list, min_range = 0, max_range = 1):
    
    # copy existing data to a new workable instance
    new_data = data.copy()
    
    # calculate global minimum and global maximum of the data
    min_value = np.matrix(new_data).min()
    max_value = np.matrix(new_data).max()
    
    # normalize data using formula x_scaled = (x - min_value)/(max_value - min_value)
    new_data -= min_value
    new_data *= ( 1 / (max_value - min_value))
    
    # return global minimum, glubal maximum and the normalized data set
    return( new_data, min_value, max_value)


# set iris to a numpy matrix from the iris data
iris = np.matrix(datasets.load_iris().data)

### a) scale all features seperatly
# initial attempt at transposing the data matrix did not work as planed, therefore loop implementation

iris_feature_vectors_normed = []

# for all rows in the iris data set apply Min-Max Normalization
for i in range(0, len(iris.data)):
    iris_feature_vectors_normed.append(min_max_scale(iris[i],0, 1))

# print first five data points of the feature normed iris data set
print('a) The first five data point of the feature vectors scaled data set are:', '\n')
for j in range (0, 5):
    print(iris_feature_vectors_normed[j][0])

print('\n')


### b) scale the full dataset

# apply Min-Max Normalization to the full data set
iris_full_dataset_normed = min_max_scale(iris, 0, 1)

# print first five data points of the fully scaled data set
print('b) The first five data point of the fully scaled data set are:', '\n')
for i in range (0, 5):
    print(iris_full_dataset_normed[0][i])



a) The first five data point of the feature vectors scaled data set are: 

[[1.         0.67346939 0.24489796 0.        ]]
[[1.         0.59574468 0.25531915 0.        ]]
[[1.         0.66666667 0.24444444 0.        ]]
[[1.         0.65909091 0.29545455 0.        ]]
[[1.         0.70833333 0.25       0.        ]]


b) The first five data point of the fully scaled data set are: 

[[0.64102564 0.43589744 0.16666667 0.01282051]]
[[0.61538462 0.37179487 0.16666667 0.01282051]]
[[0.58974359 0.3974359  0.15384615 0.01282051]]
[[0.57692308 0.38461538 0.17948718 0.01282051]]
[[0.62820513 0.44871795 0.16666667 0.01282051]]


### Exercise 2. Z-Score normalization

In [ ]:
# slice the original dataset by column
#sepal_length_norm = min_max_scale(iris.data[:, 0:1], 0, 1)
#sepal_width_norm = min_max_scale(iris.data[:, 1:2], 0, 1)
#petal_length_norm = min_max_scale(iris.data[:, 2:3], 0, 1)
#petal_width_norm = min_max_scale(iris.data[:, 3:4], 0, 1)

#print('Min-max normalization of the iris dataset for sepal length, using feature minimum', sepal_length_norm[0],
#      'and feature maximum', sepal_length_norm[1], 'is:')
#print(sepal_length_norm[2], '\n')
#
#print('Min-max normalization of the iris dataset for sepal length, using feature minimum', sepal_width_norm[0],
#      'and feature maximum', sepal_width_norm[1], 'is:')
#print(sepal_width_norm[2], '\n')
#
#print('Min-max normalization of the iris dataset for sepal length, using feature minimum', petal_length_norm[0],
#      'and feature maximum', petal_length_norm[1], 'is:')
#print(petal_length_norm[2], '\n')
#
#print('Min-max normalization of the iris dataset for sepal length, using feature minimum', petal_width_norm[0],
#      'and feature maximum', petal_width_norm[1], 'is:')
#print(petal_width_norm[2], '\n')

# b) scale the full dataset

#A = iris.data[:, :1]
#B = iris.data[:, 1:2]
#C = iris.data[:, 2:3]
#D = iris.data[:, 3:4]

#print(A)
#print(B)
#print(C)
#print(D)

### Exercise 3. Plotting I