Name - Matrikelnummer 
1) Pham, Ngoc Anh Trung - 7176267 <br>
2) Viktor Vironski - 4330455 <br>
3) Andy Disser - 5984875 <br>

In [1]:
import numpy as np

from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
data = iris.data

In [98]:
def gaussian(data, mue, sigma):
    """
    Calculate the probability of a multivariate gaussian.
    
    Parameters
    ----------
       - x: feature
       - mue: array of k mues
       - sigma: covariance matrix
       
    Returns
    -------
       - pobability for a point x in the given normal distribution N(mu,sigma)
    """
    scaling_factor = np.divide(1,(np.sqrt((2* np.pi)**len(mue) * np.linalg.det(sigma))))
    e_function = np.sum(-0.5*np.matmul((data-mue),np.linalg.inv(sigma))* (data-mue), axis=1)

    prob = scaling_factor * e_function
    return prob

In [ ]:
def GMM(data, kcomps):
    """
    Apply Gaussian Mixture Model to the data with a given number of clusters.
    
    Parameters
    ----------
       - data: Dataset with rows assumed to be data points.
       - kcomps: Number of clusters.
       
    Returns
    -------
       - returns the respective mean μ, covariance matrix Σ, and weights ϕ for each component.
       
    """    
    # initialize the data
    # divide the dataset into nearly evenly sized groups  
    num_samples = len(data)
    samples_per_group = num_samples // kcomps
    
    # calculate the initial mue and sigma
    mue = np.zeros([kcomps, data.shape[1]])
    cov_matrix = np.zeros([kcomps, data.shape[1], data.shape[1]])
    
    for i in rage(kcomps):
        mue[i] = np.mean(data[i:(i+1)*samples_per_group], axis=0)
        cov_matrix[i] = np.cov(data[i:(i+1)*samples_per_group], rowvar=False)
        if i == kcomps-1:
            mue[i] = np.mean(data[i:], axis=0)
            cov_matrix[i] = np.cov(data[i:], rowvar=False)
    
    # initial weight
    weights = np.full([kcomps], 1/kcomps)
    
    responsibility_matrix = np.empty([num_samples, kcomps])

    while True:
        
        # Estimation-step: Evaluate the responsibilities
        prob_without_weight = np.empty([num_samples, kcomps])
        
        for i in range(kcomps):
            prob_without_weight[i] = gaussian(data, mue[i], sigma[i])
        
        prob_with_weight = prob_without_weight * weights
        
        sum_probs = np.sum(prob_with_weight, axis=1).reshape(num_samples,1)
        
        responsibility_matrix = np.divide(prob_with_weight, sum_probs)

        # Maximization-step: 
        sum_responsibilities = np.sum(responsibility_matrix, axis=0)
        
        
        for i in range(kcomps):
            # update mue
            numerator = np.sum(responsibility_matrix[:,i].reshape(num_samples,1)*data, axis=0)
            denumerator = sum_responsibilities[i]
            mue[i] = np.divide(numerator,denumerator)
            
            # update sigma
            # (x-mue) * (x-mue) T
            x_minus_mue = data - mue[i]
            
            numerator = np.sum(responsibility_matrix[:,i].reshape(num_samples,1)*)
            cov_matrix[0,:,:] = np.divide(numerator,denumerator)
        
    
    return mue, cov_matrix, weights

In [241]:
np.matmul(np.full((3,4),1)[0],np.transpose(np.full((3,4),1)[0]))

4

In [44]:
first_row = data[0]
first_row

array([5.1, 3.5, 1.4, 0.2])

In [63]:
sigma = np.cov(data[:10], rowvar=False)
sigma

array([[0.08488889, 0.07044444, 0.01888889, 0.00866667],
       [0.07044444, 0.09433333, 0.01722222, 0.01644444],
       [0.01888889, 0.01722222, 0.01166667, 0.00444444],
       [0.00866667, 0.01644444, 0.00444444, 0.00622222]])

In [71]:
mue = np.mean(data[:10], axis=0)
mue

array([4.86, 3.31, 1.45, 0.22])

In [48]:
np.divide(1,(np.sqrt((2* np.pi)**len(mue) * np.linalg.det(sigma))))

/Users/andy/miniconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


inf

In [101]:
gaussian(first_row,np.mean(data[:10], axis=0),np.cov(data[:10], rowvar=False))

36.98369900935825

In [120]:
np.matmul(np.transpose(data[0]),np.linalg.inv(sigma))

array([ 54.23959704,   0.55693069,  66.57230146, -92.42868518])

In [121]:
np.matmul(np.matmul(np.transpose(data[0]),np.linalg.inv(sigma)),data[0])

353.28668732257825

In [146]:
np.matmul(np.matmul(np.transpose(data[1]),np.linalg.inv(sigma)),data[1])

338.5157169563107

In [159]:
# richtig Lösung für den e-Teil
x = np.sum(-0.5*np.matmul((data-mue),np.linalg.inv(sigma))* (data-mue), axis=1)

In [160]:
y = np.sum(-0.5*np.matmul((data-mue),np.linalg.inv(sigma))* (data-mue), axis=1)

In [169]:
z = np.stack((x,y,x), axis=-1)

In [170]:
a = [0,1,5]

In [171]:
z * a

array([[-0.00000000e+00, -1.09184120e+00, -5.45920602e+00],
       [-0.00000000e+00, -3.04799211e+00, -1.52399605e+01],
       [-0.00000000e+00, -1.17544572e+00, -5.87722859e+00],
       [-0.00000000e+00, -1.32251956e+00, -6.61259780e+00],
       [-0.00000000e+00, -1.68373260e+00, -8.41866302e+00],
       [-0.00000000e+00, -3.62870595e+00, -1.81435297e+01],
       [-0.00000000e+00, -1.88500658e+00, -9.42503289e+00],
       [-0.00000000e+00, -3.87797722e-01, -1.93898861e+00],
       [-0.00000000e+00, -1.52783096e+00, -7.63915478e+00],
       [-0.00000000e+00, -2.24912761e+00, -1.12456380e+01],
       [-0.00000000e+00, -2.42853978e+00, -1.21426989e+01],
       [-0.00000000e+00, -3.88860694e+00, -1.94430347e+01],
       [-0.00000000e+00, -1.34100602e+00, -6.70503012e+00],
       [-0.00000000e+00, -6.10219224e+00, -3.05109612e+01],
       [-0.00000000e+00, -1.96292598e+01, -9.81462992e+01],
       [-0.00000000e+00, -8.19884806e+00, -4.09942403e+01],
       [-0.00000000e+00, -1.31278405e+01

In [186]:
b= np.sum(z*a, axis=1).reshape(150,1)
b

array([[-6.55104722e+00],
       [-1.82879526e+01],
       [-7.05267431e+00],
       [-7.93511736e+00],
       [-1.01023956e+01],
       [-2.17722357e+01],
       [-1.13100395e+01],
       [-2.32678633e+00],
       [-9.16698574e+00],
       [-1.34947656e+01],
       [-1.45712387e+01],
       [-2.33316416e+01],
       [-8.04603614e+00],
       [-3.66131534e+01],
       [-1.17775559e+02],
       [-4.91930883e+01],
       [-7.87670429e+01],
       [-1.61037717e+01],
       [-3.15601174e+01],
       [-9.49787267e+00],
       [-3.03493578e+01],
       [-2.05038358e+01],
       [-9.33176556e+01],
       [-1.03169487e+02],
       [-1.28401563e+02],
       [-2.52085370e+01],
       [-3.09912691e+01],
       [-5.76908537e+00],
       [-1.37935609e+01],
       [-1.97485910e+01],
       [-1.46101070e+01],
       [-9.16195233e+01],
       [-1.21261712e+02],
       [-6.07087793e+01],
       [-6.81066260e+00],
       [-4.80761892e+01],
       [-6.41036419e+01],
       [-4.46504812e+01],
       [-9.6

In [195]:
responisbility_matrix = np.divide(z*a, b.reshape(150,1))
responisbility_matrix

array([[0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.        , 0.16666667, 0.83333333],
       [0.

In [198]:
responisbility_matrix[:,0].reshape(150)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [201]:
data * responisbility_matrix[:,1].reshape(150,1)

array([[0.85      , 0.58333333, 0.23333333, 0.03333333],
       [0.81666667, 0.5       , 0.23333333, 0.03333333],
       [0.78333333, 0.53333333, 0.21666667, 0.03333333],
       [0.76666667, 0.51666667, 0.25      , 0.03333333],
       [0.83333333, 0.6       , 0.23333333, 0.03333333],
       [0.9       , 0.65      , 0.28333333, 0.06666667],
       [0.76666667, 0.56666667, 0.23333333, 0.05      ],
       [0.83333333, 0.56666667, 0.25      , 0.03333333],
       [0.73333333, 0.48333333, 0.23333333, 0.03333333],
       [0.81666667, 0.51666667, 0.25      , 0.01666667],
       [0.9       , 0.61666667, 0.25      , 0.03333333],
       [0.8       , 0.56666667, 0.26666667, 0.03333333],
       [0.8       , 0.5       , 0.23333333, 0.01666667],
       [0.71666667, 0.5       , 0.18333333, 0.01666667],
       [0.96666667, 0.66666667, 0.2       , 0.03333333],
       [0.95      , 0.73333333, 0.25      , 0.06666667],
       [0.9       , 0.65      , 0.21666667, 0.06666667],
       [0.85      , 0.58333333,

In [220]:
test = np.array([1,2,3])
np.repeat(test[np.newaxis,:],2, axis=1)

array([[1, 1, 2, 2, 3, 3]])

In [221]:
np.sum(responisbility_matrix, axis=0).reshape

array([  0.,  25., 125.])

In [232]:
responisbility_matrix[:,0].reshape(150,1).shape

(150, 1)

In [235]:
responisbility_matrix[:,1].reshape(150,1)*data

array([[0.85      , 0.58333333, 0.23333333, 0.03333333],
       [0.81666667, 0.5       , 0.23333333, 0.03333333],
       [0.78333333, 0.53333333, 0.21666667, 0.03333333],
       [0.76666667, 0.51666667, 0.25      , 0.03333333],
       [0.83333333, 0.6       , 0.23333333, 0.03333333],
       [0.9       , 0.65      , 0.28333333, 0.06666667],
       [0.76666667, 0.56666667, 0.23333333, 0.05      ],
       [0.83333333, 0.56666667, 0.25      , 0.03333333],
       [0.73333333, 0.48333333, 0.23333333, 0.03333333],
       [0.81666667, 0.51666667, 0.25      , 0.01666667],
       [0.9       , 0.61666667, 0.25      , 0.03333333],
       [0.8       , 0.56666667, 0.26666667, 0.03333333],
       [0.8       , 0.5       , 0.23333333, 0.01666667],
       [0.71666667, 0.5       , 0.18333333, 0.01666667],
       [0.96666667, 0.66666667, 0.2       , 0.03333333],
       [0.95      , 0.73333333, 0.25      , 0.06666667],
       [0.9       , 0.65      , 0.21666667, 0.06666667],
       [0.85      , 0.58333333,

In [ ]:
from random import random
from pyparsing import original_text_for
from sklearn import cluster, datasets
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np
import copy
import matplotlib.pyplot as plt
import matplotlib as mpl


def hungarian_matching(cluster_index, gt_label):
    """
    Match the cluster to the actual classes with minimal cost.
    Inputs:
    - cluster_index : an array containing the cluster indices
    - gt_label : an array containing the actual classification of data
    Output:
    - the minimum number of missclassification / minimum cost
    """
    
    # The number of components / clusters
    kcomps = np.size(np.unique(gt_label))

    # Initialize the cost matrix
    cost_matrix = np.zeros((kcomps, kcomps))

    # Construct the cost matrix
    for i in range(kcomps):
        for j in range(kcomps):
            # Get all indices where the clustering result equals to i ( all indices of the
            # point which assigned to cluster i by the algorithm)
            indices = np.where(cluster_index == i)

            # The cost assigning cluster i to class j equals to the number of points that are assigned
            # to cluster i and at the same time not belong to class j.
            cost_matrix[i, j] = np.size(target[indices][target[indices] != j])

    origin_cost_matrix = cost_matrix

    # Step 1: subtract the minimum of the row from each entry of that row
    cost_matrix = cost_matrix - np.apply_over_axes(np.amin, cost_matrix, 1)

    # Step 2: subtract the minimum of the column from each entry of that column
    cost_matrix = np.transpose(np.transpose(cost_matrix) - np.apply_over_axes(np.amin, cost_matrix, 0))


    # Step 3: Draw minimum lines that cover all zeros.
    # For this step i will take reference from this page:
    # https://en.wikipedia.org/wiki/Hungarian_algorithm
    while True:
        
        # Initilization the needed variables.
        starred_matrix = np.zeros((kcomps, kcomps))
        primed_matrix = np.zeros((kcomps, kcomps))
        assigned_columns = set()
        assigned_rows = set()
        covered_columns = set()
        covered_rows = set()

        # Step 3.1 : Assign as much row as possible
        for i in range(kcomps):

            j = np.argmin(cost_matrix[i, :])    # The first entry in row i that equals 0

            if (j not in assigned_columns):
                assigned_rows.add(i)
                # Update starred matrix
                starred_matrix[i, j] = 1
            
            assigned_columns.add(j)             # Add it to the assigned columns

        while True:  

            # Step 3.2 : Cover all columns that having an assignment / having starred zero
            for i in range(kcomps):
                for j in range(kcomps):
                    if (starred_matrix[i, j] == 1):
                        covered_columns.add(j)

            # Step 3.3 : Find the zeros that are not lying under an assigned column and prime it
            indices = np.where(cost_matrix == 0)

            row_indices, column_indices = indices[0], indices[1]

            for i in range(np.size(indices[0])):
                # not lying under an assigned column
                if (column_indices[i] not in covered_columns): #starred_matrix[row_indices[i], column_indices[i]] == 0 :
                
                    primed_matrix[row_indices[i], column_indices[i]] = 1  # Prime this zero

                    
                    starred_zero_index = np.zeros(2)
                    there_is_starred_zero = False
                    for j in range(kcomps):
                        # Check if there is a starred zero on this line.
                        if starred_matrix [row_indices[i], j] == 1:
                            starred_zero_index = row_indices[i], j
                            there_is_starred_zero = True
                            break
                    
                    # If the zero is on the same line as a starred zero/ on the same line lying a starred zero, 
                    # cover the corresponding line, and uncover the column of the starred zero
                    if there_is_starred_zero:
                        covered_rows.add(row_indices[i])
                        covered_columns.remove(starred_zero_index[1])
                    else:
                        # If a non-covered zero has no assigned zero on its row, perform the following steps :
                        # Step 1: Find a starred zero on the corresponding column. 
                        # If there is one, go to Step 2, else, stop.
                        # Step 2: Find a primed zero on the corresponding row 
                        # (there should always be one). Go to Step 1.

                        # For all zeros encountered during the path, star 
                        # primed zeros and unstar starred zeros, remove all covered lines and primed zeros

                        # When this whole step is done, repeat from step 3.2, i.e. we don't search
                        # for non-covered zero anymore.

                        there_is_primed_zero = True

                        curr_index = np.array([row_indices[i], column_indices[i]])
                        while there_is_primed_zero:

                            starred_zero_index = np.zeros(2)
                            there_is_starred_zero = False
                            for j in range(kcomps):
                                # Check if there is a starred zero on this column.
                                if starred_matrix [j, curr_index[1]] == 1:
                                    starred_zero_index = [j, curr_index[1]]
                                    
                                    # Unstar this starred zero
                                    starred_matrix [j, curr_index[1]] = 0
                                    
                                    there_is_starred_zero = True
                                    break

                            if there_is_starred_zero:
                                # Star this primed zero
                                starred_matrix[curr_index[0], curr_index[1]] = 1
                                
                                for j in range(kcomps):
                                    # Check if there is a primed zero on this row (there should always be one)
                                    if (primed_matrix[starred_zero_index[0], j] == 1):
                                        curr_index = [starred_zero_index[0], j]
                                        break

                            else:  # If there is no starred zero on this column, stop.
                            
                                # Star this primed zero
                                starred_matrix[curr_index[0], curr_index[1]] = 1
                                
                                break

                        break

            all_zeros_are_covered = True
            # Check here whether all zeros are covered
            for i in range(kcomps):
                for j in range(kcomps):
                    if cost_matrix[i, j] == 0 and not ((i in covered_rows) or (j in covered_columns)):
                        all_zeros_are_covered = False

            # Stop when all zeros are covered and we now have the covered column and rows.
            if all_zeros_are_covered: 
                break
                        
            # Remove all covered line and primed zeros
            covered_columns = set()
            covered_rows = set()
            primed_matrix = np.zeros((kcomps, kcomps))
                        
        covered_columns = np.array(list(covered_columns))
        covered_rows = np.array(list(covered_rows))
        
        # If the number of covered lines equal k
        if (np.size(covered_columns) + np.size(covered_rows) == kcomps):

            # Here is possible to make an assignment
            assigned_cluster = np.apply_over_axes(np.argmin, cost_matrix, 0).reshape(kcomps)

            if np.size(np.unique(assigned_cluster)) < np.size(assigned_cluster):
                # If there is duplicate, try moving one of the overlapping downward or
                # upward until it works.

                for i in assigned_cluster:
                    # If there are more than one zeros on this row
                    if (np.count_nonzero(cost_matrix[i, :], 0) > 1):
                        
                        # Search for a row that has not yet been assigned
                        for j in range(kcomps):
                            if (j not in assigned_cluster):
                                assigned_cluster[i] = j
                
            assigned_cluster = assigned_cluster.reshape(kcomps, 1)
            indices = np.concatenate((assigned_cluster, np.arange(kcomps)[:, np.newaxis]), 1)

            cost = np.sum(origin_cost_matrix[indices[:,0],indices[:,1]])

            return cost

        # Step 4: From the elements that are left, find the lowest value. 
        # Subtract this from every unmarked element and add it to every element covered by two lines.

        temp_cost_matrix = copy.deepcopy(cost_matrix)

        for i in covered_rows:
            temp_cost_matrix[i, :] = np.inf
        for j in covered_columns:
            temp_cost_matrix[:, j] = np.inf

        min_val = np.argmin(temp_cost_matrix)

        sub_matrix = np.full((kcomps, kcomps), min_val)
        add_matrix = np.full((kcomps, kcomps), 0)

        for i in covered_rows:
            sub_matrix[i, :] = 0

        for j in covered_columns:
            add_matrix[:, j] = min_val

        cost_matrix = cost_matrix - sub_matrix
        cost_matrix = cost_matrix + add_matrix


if __name__ == "__main__":
    # ============= Aufgabe 2 =============================

    # Import and access the data
    iris = datasets.load_iris()
    iris_data = iris['data']
    
    n = iris_data.shape[0]
    # Run GMM or use the result from 1b
    
    # Repeat the algorithm if it fails to converge (i.e. determinant 0 because of computation error or
    # implementation error)
    while True:  # Rerun the algorithm when in some iteration the determinant equals 0
        try:
            means, cov_matrices, weights, resp_matrix = GMM(iris_data[:150, :], 3)  # Test on the first two entries
            break
        except np.linalg.LinAlgError:
            print("Matrix has 0 determinant")
    
    # Assign the point to the cluster that having the largest resposibility
    gmm_cluster_index = np.apply_over_axes(np.argmax, resp_matrix, 1).reshape(n)

    # The true classification / ground truth label
    target = iris.target

    # The accuracy of GMM
    cost_gmm = hungarian_matching(gmm_cluster_index, target)

    # Extract the cluster index of kmeans.
    kmeans = cluster.KMeans(n_clusters=3, random_state=0).fit(iris_data)
    kmean_cluster_index = kmeans.labels_

    # The accuracy of KMeans
    cost_kmeans = hungarian_matching(kmean_cluster_index, target)

    print("The amount of samples in the right class of GMM:", n-cost_gmm)
    print("The amount of samples in the right class of Kmeans:", n-cost_kmeans)
