Name - Matrikelnummer 
1) Pham, Ngoc Anh Trung - 7176267
2) Viktor Vironski - 4330455
3) Andy Disser - 5984875

In [1]:
import numpy as np
import random
import pandas as pd
from sklearn import datasets
import matplotlib

# Aufgabe 1

### 1.1)

In [2]:
def kmeans(data, ncluster):
    """
    Implements k-means algorithm.
    
    Input:   Data as a numpy array
             number of clusters
             
    Output:  cluster index for each datapoint and the centroids
    """
    
    # select three random point from the data set as initial centroids
    # replace is set to false, since it does not make any sense to have two identical centroids
    index_centroids = np.random.choice(len(data), size=ncluster, replace=False)
    centroids = data[index_centroids, :]
    cluster_array = np.zeros(len(data))
    # repeat:
    while True:
        
        # calculate the distance of each data point to the centroids
        for i, feature in enumerate(data):
            # can I calculate the distance in one step with vectors?
            distances = np.zeros(ncluster)
            for j, centroid in enumerate(centroids):
                # calculating the euclidean distance
                dist = np.linalg.norm(feature - centroid)
                distances[j] = dist
            
            # index of the cluster the feature belongs to
            cluster_array[i] = np.argmin(distances)
            
        new_centroids = pd.DataFrame(data).groupby(by=cluster_array).mean().values
        
        if (centroids == new_centroids).all():
            break
        else:
            centroids = new_centroids
            
    return centroids, cluster_array

In [3]:
iris = datasets.load_iris()

In [4]:
centroids, cluster_array = kmeans(iris.data, 3)

In [5]:
centroids

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85384615, 3.07692308, 5.71538462, 2.05384615],
       [5.88360656, 2.74098361, 4.38852459, 1.43442623]])

In [6]:
cluster_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2.,
       1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1.,
       2., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2.])

### 1.2)

In [ ]:
def mean_dist(centroids, cluster_array, data):
    """
    Calculating the average distance of points to there nearest centroid
    
    Input:  1D np array with all the centroids
            1D np array with the cluster each point from data belongs to
            2D np array containing the data
            
    Output: average distance of all points to there closest centroid
    """
    
    # np.average is when you assign different weights to values
    # np.mean calculates the average with identical weights
    # need an 3d array which contains all the distances      
    for i, feature in enumerate(data):
        
        
        

In [8]:
centroids[0]

array([5.006, 3.428, 1.462, 0.246])

In [10]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [11]:
iris.data[0] - centroids[0]

array([ 0.094,  0.072, -0.062, -0.046])

In [12]:
np.square(iris.data[0] - centroids[0])

array([0.008836, 0.005184, 0.003844, 0.002116])

In [13]:
np.sqrt(np.square(iris.data[0] - centroids[0]))

array([0.094, 0.072, 0.062, 0.046])

In [15]:
np.linalg.norm(iris.data[0] - centroids[0])

0.14135062787267663

In [16]:
np.sqrt(np.sum(np.square(iris.data[0] - centroids[0])))

0.14135062787267663

In [ ]:
centroids_1, cluster_array_1 = kmeans(iris.data, 1)

In [ ]:
centroids_2, cluster_array_2 = kmeans(iris.data, 2)

In [ ]:
centroids_3, cluster_array_3 = kmeans(iris.data, 3)

In [ ]:
centroids_4, cluster_array_4 = kmeans(iris.data, 4)

In [ ]:
centroids_5, cluster_array_5 = kmeans(iris.data, 5)

In [ ]:
centroids_6, cluster_array_6 = kmeans(iris.data, 6)

In [ ]:
centroids_7, cluster_array_7 = kmeans(iris.data, 7)

In [ ]:
centroids_8, cluster_array_8 = kmeans(iris.data, 8)

In [ ]:
centroids_9, cluster_array_9 = kmeans(iris.data, 9)

In [ ]:
centroids_10, cluster_array_10 = kmeans(iris.data, 10)

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

In [ ]:
index_centroids = np.random.choice(len(iris.data), size=3, replace=False)
print(index_centroids)
centroids = iris.data[index_centroids, :]
print(centroids)
#print(centroids[:,:-1])

In [ ]:
np.take(centroids, [1,2,3,7,11])

In [ ]:
distances = np.zeros(3)
for j, centroid in enumerate(centroids):
    dist = np.linalg.norm(iris.data[0] - centroid)
    distances[j] = dist
    
print(distances)

In [ ]:
np.argmin(distances)

In [ ]:
iris.data[0]

In [ ]:
((7.2 - 5.1)**2 + (3.2-3.5)**2 + (6-1.4)**2 + (1.8-0.2)**2)**0.5

In [ ]:
dist = np.linalg.norm(iris.data[0] - centroids[0])
dist

In [ ]:
iris.data.shape


In [ ]:
a = np.array([[1,2],
          [3,4]])

In [ ]:
np.insert(iris.data, iris.data.shape[-1], 0, axis=1)


In [ ]:
len(iris.data)

In [ ]:
np.random.choice(4, size=4, replace=False)

In [ ]:
for i, sample in enumerate(iris.data):
    print(sample)

In [ ]:
a = iris.data[0]
a

In [ ]:
b = iris.data[1:3]
b

In [ ]:
np.linalg.norm(a - b)

In [ ]:
a - b