Viktor Vironski (4330455), Andreas Disser Matr.-Nr.: 5984875

In [36]:
import torch

In [37]:
import numpy as np

In [38]:
from sklearn import datasets

In [39]:
import pandas as pd

# Exercise 1: Min-Max normalization

### scale between $[a,b]$

$x^\prime = a + \frac{(x-min(x))*(b-a)}{max(x)-min(x)}$

In [40]:
def min_max_scale(data, min_range=0, max_range=1):
    """the valuel of data gets changed in the function"""
    new_data = data
    min_value = np.amin(new_data)
    max_value = np.amax(new_data)
    print(f"The minimum value is: {min_value}")
    print(f"The maximum value is: {max_value}")
    new_data -= min_value
    new_data *= (max_range - min_range)
    new_data = np.divide(new_data, (max_value - min_value))
    
    return new_data

In [41]:
iris = datasets.load_iris()

In [42]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [43]:
iris_data = iris["data"]
p_iris_data = pd.DataFrame(iris_data, columns=["Sepal length","Sepal width","Petal length","Petal width"])
p_iris_data

Sepal length  Sepal width  Petal length  Petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

# a) scale all featrues separately

In [44]:
min_max_scale(iris_data[0,:])

The minimum value is: 0.2
The maximum value is: 5.1


array([1.        , 0.67346939, 0.24489796, 0.        ])

In [45]:
feature_scaled_iris = np.zeros((150,4))
for i in range(len(iris_data)):
    feature_scaled_iris[i,:] = min_max_scale(iris_data[i,:])
    
feature_scaled_iris

The minimum value is: 0.0
The maximum value is: 4.8999999999999995
The minimum value is: 0.2
The maximum value is: 4.9
The minimum value is: 0.2
The maximum value is: 4.7
The minimum value is: 0.2
The maximum value is: 4.6
The minimum value is: 0.2
The maximum value is: 5.0
The minimum value is: 0.4
The maximum value is: 5.4
The minimum value is: 0.3
The maximum value is: 4.6
The minimum value is: 0.2
The maximum value is: 5.0
The minimum value is: 0.2
The maximum value is: 4.4
The minimum value is: 0.1
The maximum value is: 4.9
The minimum value is: 0.2
The maximum value is: 5.4
The minimum value is: 0.2
The maximum value is: 4.8
The minimum value is: 0.1
The maximum value is: 4.8
The minimum value is: 0.1
The maximum value is: 4.3
The minimum value is: 0.2
The maximum value is: 5.8
The minimum value is: 0.4
The maximum value is: 5.7
The minimum value is: 0.4
The maximum value is: 5.4
The minimum value is: 0.3
The maximum value is: 5.1
The minimum value is: 0.3
The maximum value is: 5

array([[1.        , 0.67346939, 0.24489796, 0.        ],
       [1.        , 0.59574468, 0.25531915, 0.        ],
       [1.        , 0.66666667, 0.24444444, 0.        ],
       [1.        , 0.65909091, 0.29545455, 0.        ],
       [1.        , 0.70833333, 0.25      , 0.        ],
       [1.        , 0.7       , 0.26      , 0.        ],
       [1.        , 0.72093023, 0.25581395, 0.        ],
       [1.        , 0.66666667, 0.27083333, 0.        ],
       [1.        , 0.64285714, 0.28571429, 0.        ],
       [1.        , 0.625     , 0.29166667, 0.        ],
       [1.        , 0.67307692, 0.25      , 0.        ],
       [1.        , 0.69565217, 0.30434783, 0.        ],
       [1.        , 0.61702128, 0.27659574, 0.        ],
       [1.        , 0.69047619, 0.23809524, 0.        ],
       [1.        , 0.67857143, 0.17857143, 0.        ],
       [1.        , 0.75471698, 0.20754717, 0.        ],
       [1.        , 0.7       , 0.18      , 0.        ],
       [1.        , 0.66666667,

# b) scaling the entire dataset

In [46]:
scaled_all_data = min_max_scale(iris_data)
pd.DataFrame(scaled_all_data, columns=["Sepal length","Sepal width","Petal length","Petal width"])

The minimum value is: 0.0
The maximum value is: 5.9


Sepal length  Sepal width  Petal length  Petal width
0        0.830508     0.559322      0.203390          0.0
1        0.796610     0.474576      0.203390          0.0
2        0.762712     0.508475      0.186441          0.0
3        0.745763     0.491525      0.220339          0.0
4        0.813559     0.576271      0.203390          0.0
..            ...          ...           ...          ...
145      0.745763     0.118644      0.491525          0.0
146      0.745763     0.101695      0.525424          0.0
147      0.762712     0.169492      0.542373          0.0
148      0.661017     0.186441      0.525424          0.0
149      0.694915     0.203390      0.559322          0.0

[150 rows x 4 columns]

# tests