Andreas Disser
Matr.-Nr.: 5984875

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
from sklearn import datasets

In [22]:
import pandas as pd

# Exercise 1: Min-Max normalization

### scale between $[a,b]$

$x^\prime = a + \frac{(x-min(x))*(b-a)}{max(x)-min(x)}$

In [26]:
def min_max_scale(data, min_range=0, max_range=1):
    """the valuel of data gets changed in the function"""
    new_data = data
    min_value = np.amin(new_data)
    max_value = np.amax(new_data)
    print(f"The minimum value is: {min_value}")
    print(f"The maximum value is: {max_value}")
    new_data -= min_value
    new_data *= (max_range - min_range)
    new_data = np.divide(new_data, (max_value - min_value))
    
    return new_data

In [6]:
iris = datasets.load_iris()

In [33]:
iris.data[0]

array([0.7, 1.4, 0.3, 0. ])

In [24]:
iris_data = iris["data"]
p_iris_data = pd.DataFrame(iris_data, columns=["Sepal length","Sepal width","Petal length","Petal width"])
p_iris_data

Sepal length  Sepal width  Petal length  Petal width
0             0.8          1.5           0.4          0.1
1             0.6          1.0           0.4          0.1
2             0.4          1.2           0.3          0.1
3             0.3          1.1           0.5          0.1
4             0.7          1.6           0.4          0.1
..            ...          ...           ...          ...
145           2.4          1.0           4.2          2.2
146           2.0          0.5           4.0          1.8
147           2.2          1.0           4.2          1.9
148           1.9          1.4           4.4          2.2
149           1.6          1.0           4.1          1.7

[150 rows x 4 columns]

# a) scale all featrues separately

In [30]:
min_max_scale(iris_data[0,:])

The minimum value is: 0.0
The maximum value is: 1.4


array([0.5       , 1.        , 0.21428571, 0.        ])

In [34]:
feature_scaled_iris = np.zeros((150,4))
for i in range(len(iris_data)):
    feature_scaled_iris[i,:] = min_max_scale(iris_data[i,:])
    
feature_scaled_iris

The minimum value is: 0.0
The maximum value is: 1.4
The minimum value is: 0.0
The maximum value is: 0.9
The minimum value is: 0.0
The maximum value is: 1.1
The minimum value is: 0.0
The maximum value is: 1.0
The minimum value is: 0.0
The maximum value is: 1.5
The minimum value is: 0.0
The maximum value is: 1.5999999999999999
The minimum value is: 0.0
The maximum value is: 1.2
The minimum value is: 0.0
The maximum value is: 1.2999999999999998
The minimum value is: 0.0
The maximum value is: 0.7999999999999999
The minimum value is: 0.0
The maximum value is: 1.1
The minimum value is: 0.0
The maximum value is: 1.6
The minimum value is: 0.0
The maximum value is: 1.2999999999999998
The minimum value is: 0.0
The maximum value is: 1.0
The minimum value is: 0.0
The maximum value is: 1.0
The minimum value is: 0.0
The maximum value is: 1.9
The minimum value is: 0.0
The maximum value is: 2.1000000000000005
The minimum value is: 0.0
The maximum value is: 1.5999999999999999
The minimum value is: 0.0


array([[5.00000000e-01, 1.00000000e+00, 2.14285714e-01, 0.00000000e+00],
       [5.55555556e-01, 1.00000000e+00, 3.33333333e-01, 0.00000000e+00],
       [2.72727273e-01, 1.00000000e+00, 1.81818182e-01, 0.00000000e+00],
       [2.00000000e-01, 1.00000000e+00, 4.00000000e-01, 0.00000000e+00],
       [4.00000000e-01, 1.00000000e+00, 2.00000000e-01, 0.00000000e+00],
       [5.00000000e-01, 1.00000000e+00, 2.50000000e-01, 0.00000000e+00],
       [8.33333333e-02, 1.00000000e+00, 1.66666667e-01, 0.00000000e+00],
       [4.61538462e-01, 1.00000000e+00, 3.07692308e-01, 0.00000000e+00],
       [6.59194921e-16, 1.00000000e+00, 3.75000000e-01, 0.00000000e+00],
       [5.45454545e-01, 1.00000000e+00, 4.54545455e-01, 0.00000000e+00],
       [6.25000000e-01, 1.00000000e+00, 2.50000000e-01, 0.00000000e+00],
       [3.07692308e-01, 1.00000000e+00, 3.84615385e-01, 0.00000000e+00],
       [5.00000000e-01, 1.00000000e+00, 4.00000000e-01, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 1.00000000e

# b) scaling the entire dataset

In [27]:
scaled_all_data = min_max_scale(iris_data)
pd.DataFrame(scaled_all_data, columns=["Sepal length","Sepal width","Petal length","Petal width"])

The minimum value is: 0.0
The maximum value is: 5.9


Sepal length  Sepal width  Petal length  Petal width
0        0.135593     0.254237      0.067797     0.016949
1        0.101695     0.169492      0.067797     0.016949
2        0.067797     0.203390      0.050847     0.016949
3        0.050847     0.186441      0.084746     0.016949
4        0.118644     0.271186      0.067797     0.016949
..            ...          ...           ...          ...
145      0.406780     0.169492      0.711864     0.372881
146      0.338983     0.084746      0.677966     0.305085
147      0.372881     0.169492      0.711864     0.322034
148      0.322034     0.237288      0.745763     0.372881
149      0.271186     0.169492      0.694915     0.288136

[150 rows x 4 columns]

# tests