Name - Matrikelnummer 
1) Pham, Ngoc Anh Trung - 7176267
2) Viktor Vironski - 4330455
3) Andy Disser - 5984875

In [1]:
import numpy as np
import random
import pandas as pd
from sklearn import datasets
import matplotlib

# Aufgabe 1

### 1.1)

In [2]:
def kmeans(data, ncluster):
    """
    Implements k-means algorithm.
    
    Input:   Data as a numpy array
             number of clusters
             
    Output:  cluster index for each datapoint and the centroids
    """
    
    # select three random point from the data set as initial centroids
    # replace is set to false, since it does not make any sense to have two identical centroids
    index_centroids = np.random.choice(len(data), size=ncluster, replace=False)
    centroids = data[index_centroids, :]
    cluster_array = np.zeros(len(data))
    # repeat:
    while True:
        
        # calculate the distance of each data point to the centroids
        for i, feature in enumerate(data):
            # can I calculate the distance in one step with vectors?
            distances = np.zeros(ncluster)
            for j, centroid in enumerate(centroids):
                # calculating the euclidean distance
                dist = np.linalg.norm(feature - centroid)
                distances[j] = dist
            
            # index of the cluster the feature belongs to
            cluster_array[i] = np.argmin(distances)
            
        new_centroids = pd.DataFrame(data).groupby(by=cluster_array).mean().values
        
        if (centroids == new_centroids).all():
            break
        else:
            centroids = new_centroids
            
    return centroids, cluster_array

In [3]:
iris = datasets.load_iris()

In [4]:
centroids, cluster_array = kmeans(iris.data, 3)

In [5]:
centroids

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85384615, 3.07692308, 5.71538462, 2.05384615],
       [5.88360656, 2.74098361, 4.38852459, 1.43442623]])

In [6]:
cluster_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2.,
       1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1.,
       2., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2.])

### 1.2)

In [36]:
def mean_dist(centroids, cluster_array, data):
    """
    Calculating the average distance of points to there nearest centroid
    
    Input:  1D np array with all the centroids
            1D np array with the cluster each point from data belongs to
            2D np array containing the data
            
    Output: average distance of all points to there closest centroid
    """
    
    # np.average is when you assign different weights to values
    # np.mean calculates the average with identical weights
    # need an 3d array which contains all the distances 

    sum_dist = 0
    for i, feature in enumerate(data):
        sum_dist += np.linalg.norm(data[i] - centroids[int(cluster_array[i])])
        
    return sum_dist / len(data)
        
        

In [ ]:
def calculte_mean_dists(data, min_clusters=1, max_clusters=10):
    """
    Calculates the mean distance of all points to there nearest cluster and
    plots the results from min_clusters until max_clusters in a line graph.
    
    Input:    Dataset
    
    Output:   Line graph with the mean distances for each numer of clusters
    """
    
    

In [37]:
centroids

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85384615, 3.07692308, 5.71538462, 2.05384615],
       [5.88360656, 2.74098361, 4.38852459, 1.43442623]])

In [38]:
cluster_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2.,
       1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1.,
       2., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2.])

In [41]:
mean_dist(centroids, cluster_array, iris.data)

0.6481657935591552